# Generated by Django 5.0.6 on 2024-05-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('employee_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('salary', models.FloatField()),
                ('retirement', models.DateField()),
                ('other_benefits', models.FloatField()),
                ('total_benefits', models.FloatField()),
                ('total_compensation', models.FloatField()),
            ],
        ),
    ]
