# Generated by Django 5.0.6 on 2024-05-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0003_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='other_benefits',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='retirement',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='total_benefits',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='total_compensation',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
